### ISSUE TITLE
Realtime charts with firebase

### ISSUE THREAD

**Issue by leoelcoder** [matheusdavidson/ember-cli-morris-charts#2]
The data attribute for morris charts js need to be a json objects array,

I wonder if is posibble to pass a store.findAll('model') results to be listening changes from firebase
backend.

My model for example

```
    import DS from 'ember-data';

    export default DS.Model.extend({
        label: DS.attr('string'),
        value: DS.attr('string')
    });
```

I've made some tests without success, 
converting the results to array doesnt work.

I will to submit the better code that I can generate for this.

regards!!

**Comment by leoelcoder** [comment]
Well well here my temporary solution
only for Donut chart

I have installed emberfire and ember-cli-morris-charts
I've configured properly my firebase app and my config/enviroment.js file

so:

Model

    import DS from 'ember-data';
    export default DS.Model.extend({
        label: DS.attr('string'),
        value: DS.attr('string')
    });


I've changed addon ember-cli-morris-charts

addon/components/morris-charts.js

    setOptions: function() {
        var options = this.get('options');
        options.element = this.$().attr('id');
        if (typeof this.get('data').type == 'function') {
            options.data = [];
            this.get('data').forEach(function(b){
                options.data.push({
                    label:b.get('label'),
                    value:b.get('value'),
                });
            });
        }else{
             options.data = this.get('data');
        }
        
        /* REST OF THE OPTIONS ...... */       

        this.set('options', options);
        return options;
    }

A normal array variable has no **type function**, so I verify if **data** parameter has that function (I looking for better solution)

if **data** has **type function** means we have a store.findAll('model') results.
and then we create a normal array with the object from ember-data model


And finally apply the same condition inte observer **data.length**
    
    listenDataChanges: function() {
        var instance = this.get('instance');
        if (typeof this.get('data').type == 'function') {
            var data = [];
            this.get('data').forEach(function(b){
                console.log(b);
                data.push({
                    label:b.get('label'),
                    value:b.get('value'),
                });
            });
            instance.setData(data);
        }else{
            instance.setData(this.get('data'));
        }
    }.observes('data.length'),

**Comment by herom** [comment]
Instead of observing `data.length` you could make shure that your received data is an array and rely on a computed property on `data.[]` like

```javascript
computedData: Ember.computed('data.[]', function () {})
```

**Comment by leoelcoder** [comment]
Well, to get the changes of values from firebase a try this:
    
    listenDataChanges: function() {
        var instance = this.get('instance');
        if (typeof this.get('data').type == 'function') {
            var data = [];
            this.get('data').forEach(function(b){
                data.push({
                    label:b.get('label'),
                    value:b.get('value'),
                });
            });
            instance.setData(data);
        }else{
            instance.setData(this.get('data'));
        }
    }.observes('data.length', 'data.@each.label','data.@each.value'),

observing each property of the objects in the array, 

I'm going to try your suggestion also. :D
